"use client"

import { useEffect, useState } from "react"

const categories = {
  Coffee: [["Signature Latte", "Velvety espresso, steamed milk, house vanilla", "₦4,500", "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=700&q=85"], ["Caramel Cappuccino", "Double espresso, caramel, silky foam", "₦5,000", "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=700&q=85"], ["Classic Americano", "Bold espresso softened with hot water", "₦3,500", "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=700&q=85"], ["Iced Mocha", "Cold brew, cacao, milk, whipped cream", "₦5,500", "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=700&q=85"]],
  Tea: [["Matcha Latte", "Ceremonial matcha with creamy oat milk", "₦5,000", "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=700&q=85"], ["Chai Tea", "Warming spices, black tea, steamed milk", "₦4,000", "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=700&q=85"]],
  Pastries: [["Butter Croissant", "Flaky, golden, baked fresh every morning", "₦3,000", "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=700&q=85"], ["Cinnamon Roll", "Soft brioche, cinnamon, cream cheese glaze", "₦4,000", "https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=700&q=85"]],
  Breakfast: [["Avocado Toast", "Sourdough, smashed avocado, poached egg", "₦6,500", "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=700&q=85"], ["Breakfast Sandwich", "Egg, cheddar, greens, toasted brioche", "₦7,000", "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=700&q=85"]],
}
const gallery = [["https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=900&q=85", "The morning pour"], ["https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=900&q=85", "Good company"], ["https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=900&q=85", "Our corner"], ["https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=900&q=85", "Slow mornings"], ["https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85", "Fresh from the oven"], ["https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=85", "Roasted with care"]]
function Logo() { return <a className="logo" href="#top"><b>B</b><span>Brew <i>&</i> Bloom</span></a> }
function Button({ children, href = "#menu", light = false }) { return <a className={light ? "button light" : "button"} href={href}>{children} <span>↗</span></a> }
function Navbar() { const [open, setOpen] = useState(false); const links = [["About", "about"], ["Menu", "menu"], ["Gallery", "gallery"], ["Reviews", "reviews"], ["Location", "location"]]; return <header className="navbar"><Logo /><nav className={open ? "nav-links open" : "nav-links"}>{links.map(([label, id]) => <a href={`#${id}`} key={id} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-cta" href="#menu">View Menu <span>↗</span></a></nav><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}><span></span><span></span></button></header> }
function Hero() { return <section className="hero" id="top"><div className="hero-overlay" /><Navbar /><div className="hero-content"><p className="eyebrow">EST. 2020 <span>•</span> PORT HARCOURT</p><h1>Your Daily Ritual,<br /><em>Brewed Beautifully.</em></h1><p className="hero-copy">Specialty coffee, freshly baked treats, and a cozy place to slow down and enjoy the moment.</p><div className="hero-actions"><Button>View Our Menu</Button><Button href="#location" light>Visit Us</Button></div></div><div className="open-card"><span className="status-dot" /><div><small>OPEN TODAY</small><strong>7:00 AM — 9:00 PM</strong></div></div><a className="scroll-cue" href="#about"><span />Scroll to explore</a></section> }
function About() { return <section className="section about" id="about"><div className="about-images"><img className="about-main" src="https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1100&q=85" alt="Warm cafe interior" /><div className="about-detail"><img src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=500&q=85" alt="Fresh coffee being poured" /></div><div className="round-badge">MADE<br /><span>WITH</span><br />CARE</div></div><div className="about-copy"><p className="eyebrow">OUR STORY</p><h2>More Than<br /><em>Just Coffee</em></h2><p>Born from a love of exceptional coffee and meaningful conversations, Brew & Bloom was created as a place where people can pause, connect, and enjoy something beautifully made.</p><p>Every cup is a small invitation to slow down.</p><div className="stats"><div><strong>5<span>+</span></strong><small>Years brewing</small></div><div><strong>20<span>+</span></strong><small>Drinks to discover</small></div><div><strong>10k<span>+</span></strong><small>Happy guests</small></div></div><a className="text-link" href="#location">Our Story <span>↗</span></a></div></section> }
function MenuCard({ item }) { return <article className="menu-card"><div className="menu-image"><img src={item[3]} alt={item[0]} /><span /></div><div className="menu-card-body"><div><h3>{item[0]}</h3><p>{item[1]}</p></div><strong>{item[2]}</strong></div></article> }
function MenuSection() { const [category, setCategory] = useState("Coffee"); return <section className="section menu-section" id="menu"><div className="section-heading"><div><p className="eyebrow">THE MENU</p><h2>Made Fresh.<br /><em>Served Warm.</em></h2></div><p>From your first morning espresso<br />to your afternoon sweet treat.</p></div><div className="filters">{Object.keys(categories).map(name => <button className={category === name ? "active" : ""} onClick={() => setCategory(name)} key={name}>{name}</button>)}</div><div className="menu-grid">{categories[category].map(item => <MenuCard item={item} key={item[0]} />)}</div></section> }
function Featured() { return <section className="featured"><div className="feature-image"><img src="https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=900&q=85" alt="Signature honey latte" /></div><div className="feature-copy"><p className="eyebrow">TODAY&apos;S FAVORITE</p><h2>Signature<br /><em>Honey Latte</em></h2><p>A little sweet, perfectly balanced. Our house espresso meets wildflower honey and a cloud of steamed milk.</p><div className="feature-bottom"><strong>₦5,500</strong><Button href="#location" light>Try It Today</Button></div></div></section> }
function Gallery() { return <section className="section gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">A LITTLE LOOK INSIDE</p><h2>Made for<br /><em>Lingering.</em></h2></div><p>A space designed for slow mornings,<br />long conversations, and good ideas.</p></div><div className="gallery-grid">{gallery.map(([src, title], i) => <div className={`gallery-item gallery-${i + 1}`} key={src}><img src={src} alt={title} /><span>{title} <b>↗</b></span></div>)}</div></section> }
function Testimonials() { const reviews = [["Absolutely beautiful café. The coffee is excellent and the atmosphere makes you want to stay all afternoon.", "Amaka O."], ["One of the best coffee spots in the city. Their signature latte is incredible.", "Daniel E."], ["Great service, beautiful interior, and amazing pastries. Definitely coming back.", "Chidinma O."]]; return <section className="section reviews" id="reviews"><div className="reviews-heading"><p className="eyebrow">KIND WORDS</p><h2>Loved By<br /><em>Coffee People.</em></h2><div className="review-mark">“</div></div><div className="review-grid">{reviews.map(([quote, name]) => <article className="review-card" key={name}><div className="stars">★★★★★</div><p>“{quote}”</p><footer>— {name}</footer></article>)}</div></section> }
function Location() { return <section className="location" id="location"><div className="location-copy"><p className="eyebrow">FIND YOUR WAY HERE</p><h2>Come Say<br /><em>Hello.</em></h2><address>12 Garden Avenue<br />Port Harcourt, Rivers State<br />Nigeria</address><div className="contact"><a href="tel:+2348001234567">+234 800 123 4567</a><a href="mailto:hello@brewandbloom.com">hello@brewandbloom.com</a></div><div className="hours"><strong>OPENING HOURS</strong><p>Monday — Friday <span>7:00 AM — 9:00 PM</span></p><p>Saturday <span>8:00 AM — 10:00 PM</span></p><p>Sunday <span>9:00 AM — 8:00 PM</span></p></div><Button href="https://maps.google.com/?q=12+Garden+Avenue+Port+Harcourt">Get Directions</Button></div><div className="map"><div className="map-grid" /><div className="map-route route-one" /><div className="map-route route-two" /><div className="map-pin">B</div><div className="map-label">Brew & Bloom<br /><small>12 Garden Avenue</small></div><span className="map-street street-one">GARDEN AVE</span><span className="map-street street-two">RUMUOLA ROAD</span></div></section> }
function CTA() { return <section className="cta"><div className="cta-overlay" /><div className="cta-content"><p className="eyebrow">YOUR TABLE IS WAITING</p><h2>Your Next Great<br /><em>Coffee Is Waiting.</em></h2><p>Drop by, grab your favorite drink, and stay awhile.</p><Button>View Menu</Button></div></section> }
function Footer() { return <footer className="footer"><div className="footer-top"><div className="footer-brand"><Logo /><p>A warm place for good coffee,<br />fresh food, and better moments.</p></div><div><h4>Explore</h4><a href="#about">About</a><a href="#menu">Menu</a><a href="#gallery">Gallery</a><a href="#reviews">Reviews</a></div><div><h4>Say hello</h4><a href="mailto:hello@brewandbloom.com">hello@brewandbloom.com</a><a href="tel:+2348001234567">+234 800 123 4567</a><p>12 Garden Avenue,<br />Port Harcourt</p></div><div><h4>Follow along</h4><div className="socials"><a href="#instagram">Instagram</a><a href="#facebook">Facebook</a><a href="#tiktok">TikTok</a><a href="#x">X</a></div></div></div><div className="footer-bottom"><span>© 2026 Brew & Bloom. All rights reserved.</span><span>Made with care <i>✦</i></span></div></footer> }
export default function Page() { useEffect(() => { document.documentElement.style.scrollBehavior = "smooth"; return () => { document.documentElement.style.scrollBehavior = "auto" } }, []); return <><Hero /><main><About /><MenuSection /><Featured /><Gallery /><Testimonials /><Location /><CTA /></main><Footer /><a href="#top" className="back-top" aria-label="Back to top">↑</a></> }
